import 'package:flutter/material.dart';

/// Una categoría de emojis, con su ícono de pestaña y una lista de
/// entradas (emoji + palabras clave en español para poder buscarlo).
class EmojiCategory {
  const EmojiCategory(this.label, this.icon, this.entries);
  final String label;
  final IconData icon;
  final List<EmojiEntry> entries;
}

class EmojiEntry {
  const EmojiEntry(this.char, this.keywords);
  final String char;

  /// Palabras sueltas en español para que la búsqueda encuentre el emoji
  /// aunque el usuario no escriba el nombre exacto (p. ej. "risa" -> 😂).
  final String keywords;
}

/// Catálogo de emojis del `EmojiPickerPanel`, agrupado por categorías. Sin
/// dependencias externas: son caracteres Unicode directos; solo hace falta que
/// la fuente del sistema los sepa dibujar.
const List<EmojiCategory> emojiCatalog = [
  EmojiCategory('Caritas', Icons.emoji_emotions_outlined, [
    EmojiEntry('😀', 'sonrisa feliz contento'),
    EmojiEntry('😃', 'sonrisa feliz contento'),
    EmojiEntry('😄', 'sonrisa feliz risa'),
    EmojiEntry('😁', 'sonrisa feliz dientes'),
    EmojiEntry('😆', 'risa carcajada'),
    EmojiEntry('😅', 'risa nervioso sudor'),
    EmojiEntry('🤣', 'risa carcajada llorar'),
    EmojiEntry('😂', 'risa llorar carcajada'),
    EmojiEntry('🙂', 'sonrisa leve'),
    EmojiEntry('🙃', 'sonrisa al reves'),
    EmojiEntry('😉', 'guino coqueto'),
    EmojiEntry('😊', 'sonrisa timido'),
    EmojiEntry('😇', 'angel inocente'),
    EmojiEntry('🥰', 'amor enamorado corazones'),
    EmojiEntry('😍', 'enamorado ojos corazon'),
    EmojiEntry('🤩', 'estrellas sorprendido genial'),
    EmojiEntry('😘', 'beso amor'),
    EmojiEntry('😗', 'beso'),
    EmojiEntry('😋', 'delicioso rico sabroso'),
    EmojiEntry('😛', 'lengua broma'),
    EmojiEntry('😜', 'lengua guino broma'),
    EmojiEntry('🤪', 'loco alocado broma'),
    EmojiEntry('😎', 'cool lentes genial'),
    EmojiEntry('🤓', 'nerd lentes'),
    EmojiEntry('🧐', 'monoculo curioso'),
    EmojiEntry('😏', 'picaro sonrisa'),
    EmojiEntry('😒', 'fastidio meh'),
    EmojiEntry('😞', 'triste decepcionado'),
    EmojiEntry('😔', 'triste pensativo'),
    EmojiEntry('😢', 'triste llorar'),
    EmojiEntry('😭', 'llorar mucho triste'),
    EmojiEntry('😤', 'enojado frustrado'),
    EmojiEntry('😠', 'enojado molesto'),
    EmojiEntry('😡', 'furioso enojado rojo'),
    EmojiEntry('🥺', 'ojitos suplica tierno'),
    EmojiEntry('😱', 'susto miedo grito'),
    EmojiEntry('😨', 'miedo asustado'),
    EmojiEntry('😰', 'nervioso ansioso sudor'),
    EmojiEntry('😴', 'dormido sueño'),
    EmojiEntry('🥱', 'bostezo cansado sueño'),
    EmojiEntry('🤔', 'pensando duda'),
    EmojiEntry('🤨', 'duda sospecha ceja'),
    EmojiEntry('😐', 'neutral sin expresion'),
    EmojiEntry('😑', 'neutral aburrido'),
    EmojiEntry('🙄', 'ojos en blanco fastidio'),
    EmojiEntry('😶', 'sin palabras'),
    EmojiEntry('🤯', 'mente explota sorpresa'),
    EmojiEntry('🥳', 'fiesta celebracion'),
    EmojiEntry('😷', 'enfermo cubrebocas'),
    EmojiEntry('🤒', 'enfermo fiebre'),
    EmojiEntry('🤕', 'lastimado herido'),
  ]),
  EmojiCategory('Gestos', Icons.back_hand_outlined, [
    EmojiEntry('👍', 'pulgar arriba bien like'),
    EmojiEntry('👎', 'pulgar abajo mal dislike'),
    EmojiEntry('👌', 'ok perfecto'),
    EmojiEntry('✌️', 'paz victoria'),
    EmojiEntry('🤞', 'dedos cruzados suerte'),
    EmojiEntry('🤟', 'te amo mano'),
    EmojiEntry('🤘', 'rock mano'),
    EmojiEntry('👋', 'saludo hola adios'),
    EmojiEntry('🤙', 'llamame mano'),
    EmojiEntry('💪', 'musculo fuerza'),
    EmojiEntry('🙏', 'gracias por favor rezar'),
    EmojiEntry('👏', 'aplauso felicidades'),
    EmojiEntry('🙌', 'celebracion manos arriba'),
    EmojiEntry('🤝', 'trato apreton de manos'),
    EmojiEntry('✍️', 'escribir mano'),
    EmojiEntry('👉', 'apuntar derecha'),
    EmojiEntry('👈', 'apuntar izquierda'),
    EmojiEntry('👆', 'apuntar arriba'),
    EmojiEntry('👇', 'apuntar abajo'),
    EmojiEntry('☝️', 'apuntar arriba un dedo'),
    EmojiEntry('✊', 'puño fuerza'),
    EmojiEntry('👊', 'puño choca'),
  ]),
  EmojiCategory('Corazones', Icons.favorite_border, [
    EmojiEntry('❤️', 'corazon amor rojo'),
    EmojiEntry('🧡', 'corazon naranja amor'),
    EmojiEntry('💛', 'corazon amarillo amor'),
    EmojiEntry('💚', 'corazon verde amor'),
    EmojiEntry('💙', 'corazon azul amor'),
    EmojiEntry('💜', 'corazon morado amor'),
    EmojiEntry('🖤', 'corazon negro amor'),
    EmojiEntry('🤍', 'corazon blanco amor'),
    EmojiEntry('🤎', 'corazon cafe amor'),
    EmojiEntry('💔', 'corazon roto triste'),
    EmojiEntry('❣️', 'corazon exclamacion amor'),
    EmojiEntry('💕', 'corazones amor cariño'),
    EmojiEntry('💞', 'corazones girando amor'),
    EmojiEntry('💓', 'corazon latiendo amor'),
    EmojiEntry('💗', 'corazon creciendo amor'),
    EmojiEntry('💖', 'corazon brillante amor'),
    EmojiEntry('💘', 'corazon flecha cupido'),
    EmojiEntry('💝', 'corazon regalo amor'),
  ]),
  EmojiCategory('Animales', Icons.pets_outlined, [
    EmojiEntry('🐶', 'perro mascota'),
    EmojiEntry('🐱', 'gato mascota'),
    EmojiEntry('🐭', 'raton'),
    EmojiEntry('🐹', 'hamster'),
    EmojiEntry('🐰', 'conejo'),
    EmojiEntry('🦊', 'zorro'),
    EmojiEntry('🐻', 'oso'),
    EmojiEntry('🐼', 'panda'),
    EmojiEntry('🐨', 'koala'),
    EmojiEntry('🐯', 'tigre'),
    EmojiEntry('🦁', 'leon'),
    EmojiEntry('🐮', 'vaca'),
    EmojiEntry('🐷', 'cerdo'),
    EmojiEntry('🐸', 'rana'),
    EmojiEntry('🐵', 'mono'),
    EmojiEntry('🐔', 'gallina pollo'),
    EmojiEntry('🐧', 'pinguino'),
    EmojiEntry('🐦', 'pajaro ave'),
    EmojiEntry('🦄', 'unicornio'),
    EmojiEntry('🐝', 'abeja'),
    EmojiEntry('🐢', 'tortuga'),
    EmojiEntry('🐍', 'serpiente'),
    EmojiEntry('🐳', 'ballena'),
    EmojiEntry('🐬', 'delfin'),
    EmojiEntry('🐙', 'pulpo'),
    EmojiEntry('🦋', 'mariposa'),
  ]),
  EmojiCategory('Comida', Icons.restaurant_outlined, [
    EmojiEntry('🍎', 'manzana fruta'),
    EmojiEntry('🍌', 'platano fruta'),
    EmojiEntry('🍉', 'sandia fruta'),
    EmojiEntry('🍇', 'uvas fruta'),
    EmojiEntry('🍓', 'fresa fruta'),
    EmojiEntry('🍕', 'pizza'),
    EmojiEntry('🍔', 'hamburguesa'),
    EmojiEntry('🍟', 'papas fritas'),
    EmojiEntry('🌭', 'hot dog'),
    EmojiEntry('🌮', 'taco'),
    EmojiEntry('🌯', 'burrito'),
    EmojiEntry('🍝', 'pasta espagueti'),
    EmojiEntry('🍣', 'sushi'),
    EmojiEntry('🍦', 'helado'),
    EmojiEntry('🍰', 'pastel torta'),
    EmojiEntry('🎂', 'pastel cumpleaños torta'),
    EmojiEntry('🍫', 'chocolate'),
    EmojiEntry('🍩', 'dona'),
    EmojiEntry('🍪', 'galleta'),
    EmojiEntry('☕', 'cafe'),
    EmojiEntry('🍺', 'cerveza'),
    EmojiEntry('🍷', 'vino'),
    EmojiEntry('🥤', 'refresco bebida'),
  ]),
  EmojiCategory('Actividades', Icons.sports_soccer_outlined, [
    EmojiEntry('⚽', 'futbol balon'),
    EmojiEntry('🏀', 'basquetbol baloncesto'),
    EmojiEntry('🏈', 'futbol americano'),
    EmojiEntry('⚾', 'beisbol'),
    EmojiEntry('🎾', 'tenis'),
    EmojiEntry('🏐', 'voleibol'),
    EmojiEntry('🎮', 'videojuegos control'),
    EmojiEntry('🎲', 'dado juego'),
    EmojiEntry('🎯', 'diana objetivo'),
    EmojiEntry('🎸', 'guitarra musica'),
    EmojiEntry('🎧', 'audifonos musica'),
    EmojiEntry('🎤', 'microfono cantar'),
    EmojiEntry('🎨', 'arte pintura'),
    EmojiEntry('🎬', 'cine pelicula'),
    EmojiEntry('🏆', 'trofeo ganador'),
    EmojiEntry('🥇', 'medalla oro ganador'),
    EmojiEntry('🎉', 'fiesta celebracion confeti'),
    EmojiEntry('🎊', 'fiesta confeti celebracion'),
    EmojiEntry('🎁', 'regalo'),
  ]),
  EmojiCategory('Viajes', Icons.flight_outlined, [
    EmojiEntry('🚗', 'carro auto coche'),
    EmojiEntry('🚕', 'taxi'),
    EmojiEntry('🚌', 'autobus camion'),
    EmojiEntry('🚲', 'bicicleta'),
    EmojiEntry('🏍️', 'moto motocicleta'),
    EmojiEntry('✈️', 'avion viaje'),
    EmojiEntry('🚀', 'cohete nave'),
    EmojiEntry('🚢', 'barco'),
    EmojiEntry('🚆', 'tren'),
    EmojiEntry('🗺️', 'mapa viaje'),
    EmojiEntry('🏖️', 'playa vacaciones'),
    EmojiEntry('🏝️', 'isla playa'),
    EmojiEntry('🏔️', 'montaña'),
    EmojiEntry('🗽', 'estatua libertad'),
    EmojiEntry('🏠', 'casa hogar'),
    EmojiEntry('🏢', 'edificio oficina'),
    EmojiEntry('🌆', 'ciudad atardecer'),
    EmojiEntry('🌃', 'ciudad noche'),
  ]),
  EmojiCategory('Objetos', Icons.lightbulb_outline, [
    EmojiEntry('💡', 'idea bombilla foco'),
    EmojiEntry('📱', 'celular telefono'),
    EmojiEntry('💻', 'computadora laptop'),
    EmojiEntry('⌚', 'reloj'),
    EmojiEntry('📷', 'camara foto'),
    EmojiEntry('🎥', 'video camara'),
    EmojiEntry('📚', 'libros'),
    EmojiEntry('📝', 'nota apunte lapiz'),
    EmojiEntry('✏️', 'lapiz'),
    EmojiEntry('📌', 'chincheta pin'),
    EmojiEntry('📎', 'clip'),
    EmojiEntry('🔒', 'candado cerrado'),
    EmojiEntry('🔑', 'llave'),
    EmojiEntry('🔨', 'martillo herramienta'),
    EmojiEntry('⚙️', 'engranaje configuracion'),
    EmojiEntry('💰', 'dinero bolsa'),
    EmojiEntry('💵', 'dinero billete'),
    EmojiEntry('🎓', 'graduacion birrete'),
    EmojiEntry('📅', 'calendario fecha'),
    EmojiEntry('⏰', 'alarma reloj despertador'),
  ]),
  EmojiCategory('Símbolos', Icons.tag_outlined, [
    EmojiEntry('🔥', 'fuego genial'),
    EmojiEntry('✨', 'brillos destellos'),
    EmojiEntry('⭐', 'estrella'),
    EmojiEntry('🌟', 'estrella brillante'),
    EmojiEntry('💯', 'cien puntos perfecto'),
    EmojiEntry('✅', 'check listo correcto'),
    EmojiEntry('❌', 'equis mal incorrecto'),
    EmojiEntry('❓', 'pregunta duda'),
    EmojiEntry('❗', 'exclamacion importante'),
    EmojiEntry('⚠️', 'advertencia alerta'),
    EmojiEntry('♻️', 'reciclar'),
    EmojiEntry('🔄', 'recargar actualizar'),
    EmojiEntry('🔔', 'campana notificacion'),
    EmojiEntry('💤', 'dormir zzz'),
    EmojiEntry('💬', 'globo de dialogo chat'),
    EmojiEntry('💭', 'pensamiento globo'),
    EmojiEntry('🚫', 'prohibido no'),
    EmojiEntry('🆗', 'ok listo'),
  ]),
];
